[package]
name = "rust-web-app"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["domain", "infrastructure", "usecase", "api"]
resolver = "2"

[dependencies]
domain = { workspace = true }
infrastructure = { workspace = true }
usecase = { workspace = true }
api = { workspace = true }
tokio = { workspace = true }
sea-orm = { workspace = true }
dotenvy = { workspace = true }
axum = { workspace = true }

[workspace.dependencies]
# Web & Async
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# DB
sea-orm = { version = "1.1", features = [
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "macros",
] }

# Internal
domain = { path = "domain" }
infrastructure = { path = "infrastructure" }
usecase = { path = "usecase" }
api = { path = "api" }

# Misc
thiserror = "1.0"
anyhow = "1.0"
dotenvy = "0.15"
async-trait = "0.1"
